### ISSUE TITLE
cb-kafka connector metrics

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#43]
**Is your feature request related to a problem? Please describe.**

1. when using the (go-dcp-client and go-kafka-connect-couchbase) libraries to build my own cb-kafka connector, I wish to be able to control at the connector level whether or not to start prometheus metrics collecting, and which port to run the metrics endpoint.
2. when use prometheus/grafana to visualize the metrics in k8s, it's hard to do so because the metrics in general do not have labels.
3. it's hard to tell the data rate and size of the critical (kafka or cb) metadata topic because there are no metrics about its working, which is very useful in estimating the additional resource requirements (on kafka or cb)

**Describe the solution you'd like**

1. Provide methods for application developer to start metrics collecting at specified port
2. Add some k8s default labels to the metrics (such as app, instance, pod, job, namespace)
3. Add some metrics regarding the metadata topic reads and writes

**Describe alternatives you've considered**
N/A

**Additional context**
You may need to provide different sets of labels for different types of membership. At least we must be able to tell which metrics are from which member of the dcp group.

**Comment by erayarslan** [comment]
hi @Du-Li 
we have already `/metrics` endpoint. you can see in [here](https://github.com/Trendyol/go-dcp-client#configuration) and you configure path and port.
but kubernetes labels depend your kubernetes cluster monitoring. the labels you want mostly available on kubernetes prometheus exporters. applications should not aware these.

i like the idea of metadata metrics, which is write and write latency. we will implementing this.
but metadata read metric is non sense. because application always reading metadata at the start.
after that only rebalance trigger metadata read.

thank you so much for your contribution.

**Comment by erayarslan** [comment]
`cbgo_offset_write_current`, `cbgo_offset_write_latency_ms_current` metrics available with `v0.0.40`

**Comment by Du-Li** [comment]
@erayarslan Thanks for your quick response.

Are these two metrics about writing metadata (checkpoints) to cb or kafka? Can you explain them a bit?

**Comment by erayarslan** [comment]
it measures whichever you use.
```
cbgo_offset_write_current = offset write tps
cbgo_offset_write_latency_ms_current = offset commit operation average response time in ms
```

for your configuration it's measures kafka metadata.
