### ISSUE TITLE
very high dcp latencies in v0.0.40

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#44]
**Describe the bug**
After upgrading from go-kafka-connect-couchbase v0.0.37 (do-dcp-client v0.0.39) to v0.0.40 (go-dcp-client v0.0.45), huge dcp latencies were observed (with api enabled or disabled), p99 hitting 100s. After reverting to v0.0.37, the latencies went back to normal, p99 around 6-7ms.

**To Reproduce**
1. set up couchbase, dcp-kafka connector, and kafka on k8s
2. set up prometheus to visualize the dcp latencies and total number of mutation events
3. feed workload to CB to generate 4k/s mutation updates
4. dcp latencies keep increasing all the way to 100s, while the number of events keep dropping
5. repeat the above with the two different versions

**Expected behavior**
After upgrading the versions, the same level of dcp latencies should be maintained.

**Version (please complete the following information):**
 - OS: linux/amd64
 - Golang version 1.18
 - Couchbase 6.5
 - Kafka 3.4.0

**Comment by Du-Li** [comment]
Thanks @erayarslan for your suggestion. I tested it and it worked. I also put a few metrics on prometheus/grafana.

However, I noticed that the metric `avg(cbgo_lag_current)` keeps increasing and the other metric `cbgo_dcp_latency_ms_current` was showing hundreds of milliseconds. Is this normal? Can you help by explaining a bit more than the README?

**Comment by erayarslan** [comment]
unfortunately `cbgo_lag_current` not working well when using another scope and collection. (different from _default)
and it's impossible to solve at the moment. because our stream cannot aware of other collections in bucket.
java connectors also have same issues. i test it.

`cbgo_dcp_latency_ms_current` means the gap between event create time you last read and read time.
it will decrease after your stream catchup changes.

we have still big documentation issues before v1.0.0
sorry for that.
